=== Leo7k/GenerateGUIforCLI/generateGUIforCLI_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "defaultArgumentNameValueSeparator": {
      "type": "string"
    },
    "defaultSelectMultipleValueSeparator": {
      "type": "string"
    },
    "defaultSelectMultipleQuotationSymbol": {
      "type": "string"
    },
    "defaultQuotationSymbol": {
      "type": "string"
    },
    "defaultBooleanTrue": {
      "type": "string"
    },
    "defaultBooleanFalse": {
      "type": "string"
    },
    "sections": {
      "type": "object",
      "additionalProperties": {
          "type": "object",
          "properties": {
            "displayName": {
              "type": "string"
            },
            "args": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "object",
                  "properties": {
                    "booleanTrue": {
                      "type": "string"
                    },
                    "booleanFalse": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string",
                      "enum": ["boolean", "input-file", "input-file-multiple", "number", "output-file", "string", "select-one", "select-multiple"]
                    },
                    "required": {
                      "type": "boolean"
                    },
                    "displayName": {
                      "type": "string"
                    },
                    "quotationSymbol": {
                      "type": "string"
                    },
                    "defaultValue": {
                      "type": "string"
                    },
                    "nameValueSeparator": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "type",
                    "displayName"
                  ]
                }
              ]
            }
          },
          "required": [
            "displayName",
            "args"
          ]
        }
    }
  },
  "required": [
    "defaultArgumentNameValueSeparator",
    "defaultSelectMultipleValueSeparator",
    "defaultSelectMultipleQuotationSymbol",
    "defaultQuotationSymbol",
    "defaultBooleanTrue",
    "defaultBooleanFalse",
    "sections"
  ]
}

=== Leo7k/GenerateGUIforCLI/descriptions/example.json
{
  "description": "Example CLI Application",
  "defaultArgumentNameValueSeparator": " ",
  "defaultSelectMultipleValueSeparator": ",",
  "defaultSelectMultipleQuotationSymbol": "`",
  "defaultQuotationSymbol": "'",
  "defaultBooleanTrue": "true",
  "defaultBooleanFalse": "false",
  "sections": {
    "primary": {
      "displayName": "Primary arguments",
      "args": [
        {
          "name": "--count",
          "type": "number",
          "required": true,
          "displayName": "Number of something",
          "nameValueSeparator": "="
        },
        {
          "name": "--text",
          "type": "string",
          "quotationSymbol": "'",
          "defaultValue": "dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt",
          "displayName": "Some text here"
        },
        {
          "name": "--input-file",
          "type": "input-file-multiple",
          "quotationSymbol": "`",
          "displayName": "Path to input file"
        },
        {
          "name": "/boolean-flag",
          "type": "boolean",
          "defaultValue": true,
          "displayName": "Do some stuff",
          "booleanTrue": "yes",
          "booleanFalse": "no"
        }
      ]
    },
    "secondary": {
      "displayName": "Secondary section",
      "args": [
        {
          "name": "--colors",
          "type": "select-multiple",
          "defaultValue": "G",
          "displayName": "Choose colors",
          "options": [
            {
              "value": "B",
              "displayValue": "Blue"
            },
            {
              "value": "G",
              "displayValue": "Green"
            },
            {
              "value": "R",
              "displayValue": "Red"
            }
          ]
        },
        {
          "name": "--direction",
          "type": "select-one",
          "defaultValue": "C",
          "displayName": "Choose one of",
          "options": [
            {
              "value": "L",
              "displayValue": "Left"
            },
            {
              "value": "C",
              "displayValue": "Center"
            },
            {
              "value": "R",
              "displayValue": "Right"
            }
          ]
        }
      ]
    }
  }
}
