=== Leo7k/GenerateGUIforCLI/generateGUIforCLI_schema_2019-09.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "defaultArgumentNameValueSeparator": {
      "type": "string"
    },
    "defaultSelectMultipleValueSeparator": {
      "type": "string"
    },
    "defaultSelectMultipleQuotationSymbol": {
      "type": "string"
    },
    "defaultQuotationSymbol": {
      "type": "string",
      "default": "\""
    },
    "defaultBooleanTrue": {
      "type": "string",
      "default": "true"
    },
    "defaultBooleanFalse": {
      "type": "string",
      "default": "false"
    },
    "sections": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "displayName": {
            "type": "string"
          },
          "args": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "booleanTrue": {
                  "type": "string"
                },
                "booleanFalse": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": ["boolean", "input-file", "input-file-multiple", "number", "output-file", "string", "select-one", "select-multiple"]
                },
                "required": {
                  "type": "boolean"
                },
                "displayName": {
                  "type": "string"
                },
                "dontIncludeName": {
                  "type": "boolean"
                },
                "quotationSymbol": {
                  "type": "string"
                },
               "defaultValue": {
                       "oneOf": [{
                             "type": "string"
                        },
                        {
                             "type": "boolean"
                        },
                        {
                             "type": "number"
                        }
                      ]
                 },
                "nameValueSeparator": {
                  "type": "string"
                },
                "options": {
                  "type": "array",
                  "uniqueItems": true,
                  "items": {
                     "type": "object",
                     "properties": {
                       "value": {
                         "type": "string"
                        },
                        "displayValue": {
                           "type": "string"
                        }
                     },
                     "required": [
                        "value"
                     ]
                  }
                }
              },
              "required": [
                "name",
                "type",
                "displayName"
              ]
            }
          }
        },
        "required": [
          "displayName",
          "args"
        ]
      }
    }
  },
  "required": [
    "defaultArgumentNameValueSeparator",
    "defaultSelectMultipleValueSeparator",
    "defaultSelectMultipleQuotationSymbol",
    "defaultQuotationSymbol",
    "defaultBooleanTrue",
    "defaultBooleanFalse",
    "sections"
  ]
}

=== Leo7k/GenerateGUIforCLI/descriptions/regsvr32.json
{
  "description": "regsvr32 - Register Server",
  "defaultArgumentNameValueSeparator": " ",
  "defaultSelectMultipleValueSeparator": ",",
  "defaultSelectMultipleQuotationSymbol": "`",
  "defaultQuotationSymbol": "\"",
  "defaultBooleanTrue": "true",
  "defaultBooleanFalse": "false",
  "sections": [{
      "displayName": "regsvr32GUI",
      "args": [
        {
          "name": "/u",
          "type": "boolean",
          "defaultValue": false,
          "displayName": "Unregister (call DllUnregisterServer).",
          "booleanTrueAsPresence": true
        },
        {
          "name": "/s",
          "type": "boolean",
          "defaultValue": false,
          "displayName": "Silent mode - do not display messages.",
          "booleanTrueAsPresence": true
        },
        {
          "name": "/n",
          "type": "boolean",
          "defaultValue": false,
          "displayName": "Prevent calling DllRegisterServer. This parameter requires you to also use DllInstall / DllUninstall Command line.",
          "booleanTrueAsPresence": true
        },
        {
          "name": "/i",
          "type": "string",
          "nameValueSeparator": ": ",
          "quotationSymbol": "",
          "displayName": "DllInstall / DllUninstall Command line."
        },
        {
          "name": "--input-file",
          "type": "input-file",
          "dontIncludeName": true,
          "displayName": "Path to the .dll file that will be registered / unregistered."
        },
        {
          "name": "/?",
          "type": "boolean",
          "defaultValue": false,
          "displayName": "Display help at the command prompt.",
          "booleanTrueAsPresence": true
        }
      ]
    }
  ]
}
